### PR TITLE
Make non tooling projects netstandard2.0

### PR DESCRIPTION
**Pull request by schotime**
Great project firstly.
Do you have any objections to making the projects netstandard2.0 so they can be referenced by other netstandard2.0 projects. I wanted to abstract some logic in this library but was unable to do so.

### CODE REVIEW

**Comment by adams85** [comment]
Thanks, Adam!

Sure, we can do this. Even the ASP.NET Core libs referenced in the main project (Microsoft.AspNetCore.Mvc.TagHelpers and Microsoft.AspNetCore.StaticFiles) are netstandard2.0. However, switching the project to netstandard would make perfect sense for me if we also refactored the ASP.NET Core agnostic stuff into a separate core assembly. I need to give this some more thought.

By the way, what's your reason for changing StartsWith/EndsWith/etc overloads to use strings instead of chars?

**Comment by adams85** [comment]
Ok, I think I've got it. Those overloads don't exist in netstandard2.0, do they? :)

**Comment by schotime** [comment]
Hi, yeah those overloads don't exist.

I've successfully integrated my branch into our project with the netstandard2.0 changes as is and everything seems to work as is. 

My shared library is just referencing the bundling core library and works great.

Separating the asp.net stuff could happen but I'm ok with how it is.

**Comment by schotime** [comment]
Any progress on this? I'd rather not run my own fork ;)

**Comment by adams85** [comment]
Sorry, I've been busy recently.

I needed to do some quick tests to see if this change won't break the dotnet CLI tool. It seems it's alright so I'll merge your PR and publish a new version shortly.

**Comment by schotime** [comment]
All good mate, I know what it's like.
Thanks.

**Pull request merged**
